version: "3"
services:

  backend:
    container_name: "node"
    build: ./backend/
    command: sh -c "npx knex migrate:latest && npm start"
    ports:
      - "3001:3001"
    depends_on: 
      - "database"
    links:
      - database
    restart: on-failure

  database:
    container_name: "pg"
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    volumes: 
      - /var/lib/postgresql/data
    restart: always

  frontend:
    container_name: "react"
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always

